NewBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from NewBlog.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("pages.urls", namespace="pages")),
    path("articles/", include("articles.urls", namespace="articles")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path

from accounts.views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

articles/urls.py
from django.urls import path

from articles.views import ArticleListView, ArticleDetailView

app_name = "articles"

urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="detail"),
]

pages/urls.py
from django.urls import path

from pages.views import HomeTemplateView

app_name = "pages"

urlpatterns = [
    path("", HomeTemplateView.as_view(), name="home"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

articles/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=150)
    summary = models.CharField(max_length=200, blank=True)
    body = models.TextField()
    image = models.ImageField(upload_to="images/", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", args=[str(self.id)])

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "age")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "age")

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from accounts.forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from articles.models import Article


class ArticleListView(LoginRequiredMixin, ListView):
    template_name = "article_list.html"
    model = Article
    context_object_name = "articles"


class ArticleDetailView(LoginRequiredMixin, DetailView):
    template_name = "article_detail.html"
    model = Article
    context_object_name = "article"

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = "home.html"

templates/article_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 class="text-center">This is detail page</h1>
        <h1 class="text-left"><a href="{% url 'logout' %}">Logout</a></h1>
            <h3>{{ article.title }}<a href="{% url 'articles:detail' pk=article.pk %}"></a></h3>
            <p>{{ article.summary }}</p>
            <img width="100%" src="{{ article.image.url }}" alt="article image">
            <p class="text-center">author: {{ article.author }}</p>
            <p>{{ article.body }}</p>
    </div>
{% endblock %}

templates/article_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 class="text-center">This is article page</h1>
        <h1 class="text-left"><a href="{% url 'logout' %}">Logout</a></h1>
        {% for article in articles %}
            <h3><a href="{% url 'articles:detail' pk=article.pk %}">{{ article.title }}</a></h3>
            <p>{{ article.summary }}</p>
            <img width="100%" src="{{ article.image.url }}" alt="article image">
            <p class="text-center">author: {{ article.author }}</p>
            <p>{{ article.body }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'articles:list' %}">
        <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top"
             alt="">
        Isca_nolove
    </a>
</nav>
<div class="container mt-5 mb-5 text-center">
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
</div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <p>Hello {{ user.username.upper }} !</p>
        <h1><a href="{% url 'articles:list' %}">Articles</a></h1>
        <h1><a href="{% url 'logout' %}">Logout</a></h1>
        <h1><a href="{% url 'password_change' %}">Change your password</a></h1>
        <h1><a href="{% url 'password_reset' %}">Forgot your password ?</a></h1>
    {% else %}
        <h1><a href="{% url 'login' %}">Login</a></h1>
        <h1><a href="{% url 'signup' %}">Sign up</a></h1>
    {% endif %}
{% endblock %}